NUMPY CHEAT SHEET

In [2]:
import numpy as np

In [3]:
# creating array 
a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6)])
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6,)]])


In [4]:
# initial placeholder

np.zeros((2,5))                 #(creat a array of zeros )

np.ones((3,3))                  #(creat a array of ones)

d=np.arange(10,25,5)            #(creat a array of evenly spaced values (step values))

np.linspace(0,2,9)              #(creat a array of evenly spaced values (number osf samples))

e=np.full((3,3,),7)             #(creat a constant array)

f=np.eye(3)                     #(creat 3x3 identity matrix)

np.random.random((2,2))         #(creat array with random values)

np.empty((3,2))                 #(creat an empty array)





array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
# saving and loading on disk
np.save('my_array',a)
np.savez('array.npz',a,b)
np.load('my_array.npy')

array([1, 2, 3])

In [6]:
# saving and loading text file 
#np.loadtxt("myfile.txt")        #(load txt file)

#np.genfromtxt("my_file.csv")

np.savetxt("my_array.txt",a)



In [7]:
# data types

np.int64            #(signed 64bit intger types)

np.float32          #(standard doulble-precision floating point)

np.complex128       #(complex number represented by 128 floats)

np.bool_            #(boolean type string TRUE and FALSE values)

np.object_          #(python object type)

np.string_          #(fixed-length string type)

np.unicode_         #(fixed-length unicode type)

numpy.str_

In [8]:
# inspecting your array 

a.shape             #(array dimension)

len(a)              #(length of array)

b.ndim              #(number of array dimension)

e.size              #(number of elements)

b.dtype             #(data type of array elements)

b.dtype.name        #(name of data type)

b.astype            #(convert array into different type)

<function ndarray.astype>

In [9]:
# ARRAY MATHEMATICS
    # arithmetic operations 

g= a-b
np.subtract(a,b)                #(subtraction)

b+a
np.add(b,a)                    #(addition)

a/b
np.divide(a,b)                 #(division)

a*b
np.multiply(a,b)                #(multiplication)

np.exp(b)                       #(exponentiation)

np.sqrt(b)                      #(square root)

np.sin(a)                       #(print sines of array)

np.cos(b)                       #(element wise cosine)

np.log(a)                       #(element wise natural logarithm)

e.dot(f)                        #(Dot product)

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

In [ ]:
# asking for help 
np.info(np.ndarray)

In [11]:
# comparison

a==b                    #(element wise comparison)

a<2                     #(element wise comparison)

np.array_equal(a,b)     #(array wise comparison)


False

In [12]:
# aggeregate functions

a.sum()                 #(array wise sum)

a.min()                 #(array wise  minimum values)

b.max(axis=0)           #(maximum value of an array row)

b.cumsum(axis=1)        #(cumulative sum of the elements)

a.mean()                #(mean)

np.median(b)            #(median)

np.corrcoef(b)           #(coerrelation coefficient)

np.std(b)                #(standard deviation)

1.5920810978785667

In [13]:
# copying array

h= a.view()                 #(creat a view of array with same data)

np.copy(a)                  #(creat a copy of array)

h=a.copy()                  #(creat a deep copy of the array)

In [14]:
# sorting arrays

a.sort()                            #(sort an array)

a.sort('decsending'==False)         #(sort an array acsending way)

c.sort(axis=0)                      #(sort the elements of an array's axis)


In [15]:
# subsetting, slicing, indexing 
    #subsetting 

a[2]                #(select the element at index 2)

b[1,2]              #(select the element from [row][column])

#Slicing

a[0:2]              #(select item at index 0 and 1)

b[0:2,1]            #(select item at row 0 and 1 in column 1)

b[:1]               #(select all item at row 0)

c[1,...]            #(same as 1,:,:)

a[: : -1]           #reversed array 

# boolean indexing 

a[a<2]              #(select element from a less than 2)

# fancy indexing 

b[[1,0,1,0],[0,1,2,0]]              #(select elements (1,0),(0,1),(1,2)and (0,0))

b[[1,0,1,0]][:,[0,1,2,0]]           #(select the subset of the matrix's row and colummn)




array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

In [30]:
# array manipulation

i=np.transpose(b)           #(permute array dimensions)

i.T                         #(permute array dimensions)         

#changing array shape 

b.ravel()                   #(flatten the array)

g.reshape(3,-2)             #(reshape,but don't change data)



#adding/removing elements

h.resize((2,6))             #(return new array with shape)
h

np.append(h,g)              #(append item to an array)

np.insert(a,1,5)            #(insert item in array)

np.delete(a,[1])            #(delet item from array)



# combining array

np.concatenate((a,d),axis=0)                #(concatenate arrays)

np.vstack((a,b))                            #(stack array vertically row wise)

np.r_[e,f]                                  #(stack array vertically row wise)

np.hstack((e,f))                            #(stack array horizontally column wise)

np.column_stack((a,d))                      #(creat stacked column wise array)

np.c_[a,d]                                  #(creat stacked column wise array)



# splitting array 

np.hsplit(a,3)                              #(split the array horizontally at the 3rd index)

np.vsplit(c,2)                              #(split the array vertically at the 2nd index)







[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]